ARG IMAGE_NAME=naevatec/kurento-media-server
ARG IMAGE_VERSION=7.0.0

FROM ${IMAGE_NAME}:${IMAGE_VERSION}

COPY libssl.so.1.1 /usr/lib/x86_64-linux-gnu
COPY libcrypto.so.1.1 /usr/lib/x86_64-linux-gnu

