name: Publish release

on: 
  workflow_call:
    inputs:
      version:
        description: 'Version number'
        type: string
        required: true
      force_release:
        description: 'Force release'
        required: true
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        type: string
        required: true
      force_release:
        description: 'Force release'
        required: true
        type: boolean
        default: false

jobs:

  publish-release:
    runs-on: self-hosted  
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          version=${{ github.event.inputs.version }}
          if [[ $version == v* ]]; then
            version=${version:1}
          fi
          echo "SIPRTP_VERSION=$version" >> $GITHUB_ENV>> $GITHUB_ENV
          echo "FORCE_RELEASE=${{ github.event.inputs.force_release }}" >> $GITHUB_ENV

      # Action: https://github.com/actions/download-artifact
      - name: "Copy artifacts from previous jobs"
        id: "copy-artifacts"
        uses: "actions/download-artifact@v4"
        with:
          path: "artifacts"

      - name: "Get artifacts"
        run: |
          ARTIFACT_PATH="${{ steps.copy-artifacts.outputs.download-path }}"
          mkdir -p ./artifacts
          ls -la ${ARTIFACT_PATH}
          cp  ${ARTIFACT_PATH}/debian\ packages/*.*deb ./artifacts
          cp  ${ARTIFACT_PATH}/java\ artifacts/*.jar ./artifacts
          cp  ${ARTIFACT_PATH}/js\ artifacts/*.tgz ./artifacts

      - name: Publish release
        if: ${{ env.FORCE_RELEASE == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.SIPRTP_VERSION }}
          name: ${{ env.SIPRTP_VERSION }}
          body: 'Release of version ${{ env.SIPRTP_VERSION }}'
          draft: true
          prerelease: false
          allowUpdates: true
          generateReleaseNotes: true
          artifacts: |
            ./artifacts/*.*deb
            ./artifacts/*.jar
            ./artifacts/*.tgz

      - name: cleanup
        run: |
          rm -rf ./artifacts


