name: Build and release

on:
  push:
    tags:
      - '*.*.*'
  
jobs:
  release:
    uses: "./.github/workflows/release.yml"
    with:
      version: '${{ github.ref_name }}'
      force_release: true
      image_name: 'naevatec/kurento-media-server-siprtp'
      kurento_version: '7.2.0'
      create_docker_image: false
