name: Build and release

on:
  push:
    tags:
      - 'v*.*.*'
    inputs:
      version:
        description: 'Version number'
        required: true
      force_release:
        description: 'Force release'
        type: boolean
        default: true
  
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
      force_release:
        description: 'Force release'
        required: true
        type: boolean
        default: false
      image_name:
        description: 'docker image name'
        required: false
        type: string
        default: 'naevatec/kurento-media-server-siprtp'
      kurento_version:
        description: 'Kurento version'
        required: false
        type: string
        default: '7.1.1'
      create_docker_image:
        description: 'Create docker image'
        required: false
        type: boolean
        default: false

jobs:
  build-kurento-module:
    uses: "./.github/workflows/build_kurento_module.yaml"
    with:
      version: '${{ github.event.inputs.version || github.ref_name }}'
      kurento_version: '${{ github.event.inputs.version || "7.2.0" }}'

  build-kurento-js-client:
    needs: build-kurento-module
    uses: "./.github/workflows/build_kurento_js_client.yaml"
    with:
      version: '${{ github.event.inputs.version || github.ref_name }}'
      kurento_version: '${{ github.event.inputs.version || "7.2.0" }}'

  build-kurento-java-client:
    needs: build-kurento-module
    uses: "./.github/workflows/build_kurento_java_client.yaml"
    with:
      version: '${{ github.event.inputs.version || github.ref_name }}'
      kurento_version: '${{ github.event.inputs.version || "7.2.0" }}'

  publish-release:
    needs: [build-kurento-module, build-kurento-js-client, build-kurento-java-client]
    uses: "./.github/workflows/publish_release.yaml"
    with:
      version: '${{ github.event.inputs.version || github.ref_name }}'
      force_release: '${{ github.event.inputs.force_release || "7.2.0" }}'

  build-docker-image:
    needs: build-kurento-module
    uses: "./.github/workflows/build_kurento_docker_image.yaml"
    with:
      version: '${{ github.event.inputs.version || github.ref_name }}'
      force_release: '${{ github.event.inputs.force_release || true}}'
      image_name: '${{ github.event.inputs.image_name || "naevatec/kurento-media-server-siprtp" }}'
      kurento_version: '${{ github.event.inputs.kurento_version || "7.2.0" }}'
      create_docker_image: '${{ github.event.inputs.create_docker_image || false }}'
