name: Build and release

on:
  workflow_call:
    inputs:
      version:
        description: 'Version number'
        type: string
        required: true
      force_release:
        description: 'Force release'
        required: true
        type: boolean
        default: false
      image_name:
        description: 'docker image name'
        required: false
        type: string
        default: 'naevatec/kurento-media-server-siprtp'
      kurento_version:
        description: 'Kurento version'
        required: false
        type: string
        default: '7.1.1'
      create_docker_image:
        description: 'Create docker image'
        required: false
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        type: string  
        required: true
      force_release:
        description: 'Force release'
        required: true
        type: boolean
        default: false
      image_name:
        description: 'docker image name'
        required: false
        type: string
        default: 'naevatec/kurento-media-server-siprtp'
      kurento_version:
        description: 'Kurento version'
        required: false
        type: string
        default: '7.1.1'
      create_docker_image:
        description: 'Create docker image'
        required: false
        type: boolean
        default: false

jobs:
  set-context:
    runs-on: self-hosted
    outputs:
      version: ${{ steps.get-parameters.outputs.version }}
      force: ${{ steps.get-parameters.outputs.force }}
      image: ${{ steps.get-parameters.outputs.image }}
      kurento: ${{ steps.get-parameters.outputs.kurento }}
      docker: ${{ steps.get-parameters.outputs.docker }}
    steps:
      - name: Set input parameters
        id: get-parameters
        run: |
          echo "workflow launched manually with version ${{ github.event.inputs.version }}"
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          echo "force=${{ github.event.inputs.force_release }}" >> $GITHUB_OUTPUT
          echo "image=${{ github.event.inputs.image_name }}" >> $GITHUB_OUTPUT
          echo "kurento=${{ github.event.inputs.kurento_version }}" >> $GITHUB_OUTPUT
          echo "docker=${{ github.event.inputs.create_docker_image }}" >> $GITHUB_OUTPUT


  build-kurento-module:
    needs: set-context
    uses: "./.github/workflows/build_kurento_module.yml"
    with:
      version: '${{ needs.set-context.outputs.version }}'
      kurento_version: '${{ needs.set-context.outputs.kurento }}'

  build-kurento-js-client:
    needs: [set-context, build-kurento-module]
    uses: "./.github/workflows/build_kurento_js_client.yml"
    with:
      version: '${{ needs.set-context.outputs.version }}'
      kurento_version: '${{ needs.set-context.outputs.kurento }}'

  build-kurento-java-client:
    needs: [set-context, build-kurento-module]
    uses: "./.github/workflows/build_kurento_java_client.yml"
    with:
      version: '${{ needs.set-context.outputs.version }}'
      kurento_version: '${{ needs.set-context.outputs.kurento }}'

  publish-release:
    needs: [set-context, build-kurento-module, build-kurento-js-client, build-kurento-java-client]
    uses: "./.github/workflows/publish_release.yml"
    with:
      version: '${{ needs.set-context.outputs.version }}'
      force_release: ${{ fromJson(needs.set-context.outputs['force']) }} 

  build-docker-image:
    needs: [set-context, build-kurento-module]
    uses: "./.github/workflows/build_kurento_docker_image.yml"
    with:
      version: '${{ needs.set-context.outputs.version }}'
      force_release: ${{ fromJson(needs.set-context.outputs['force']) }} 
      image_name: ${{ needs.set-context.outputs.image }} 
      kurento_version: '${{ needs.set-context.outputs.kurento }}'
      create_docker_image: ${{ fromJson(needs.set-context.outputs['docker']) }} 

  cleanup_docker:
    needs: build-docker-image
    uses: "./.github/workflows/cleanup.yml"
